### ISSUE TITLE
9/6 やること（5sprint）

### ISSUE THREAD

**Issue by novagz5** [Ishimoto0314/group4#15]

**Comment by novagz5** [comment]
マイク入力のプログラムを書いてみます

**Comment by Ishimoto0314** [comment]
「ぜろつく」進めていきます
出来るだけ、ブログにも進捗状況もかいていきます

**Comment by koki-333** [comment]
librosaの特徴抽出についてのチュートリアルを進めます。
念のためTodoの方にも貼りました。

**Comment by koki-333** [comment]
残ってるCore IO and DSPも進めます。

**Comment by Ishimoto0314** [comment]
僕も並行して進めまーす

**Comment by novagz5** [comment]
pyaudioがインストールできなくて困っています
https://arakan-pgm-ai.hatenablog.com/entry/2020/07/20/000000
https://qiita.com/r-ngtm/items/f7dc53bf713d12f6be9d

これらの記事を参考に取り組んでいます

**Comment by koki-333** [comment]
何かエラーが出てるってこと？自分はインストールできたよ

**Comment by novagz5** [comment]
本当に？なんでだ
何やってもインストールできなくて困ってる

**Comment by koki-333** [comment]
インストールするときカレントフォルダに設定してる？バージョンはあってる？

**Comment by novagz5** [comment]
何やぁインストールできます→何やってもインストールできないの間違い

どういうこと？

**Comment by novagz5** [comment]
意味不明な文章に変換される

**Comment by novagz5** [comment]
治った。すまん

**Comment by koki-333** [comment]
解決したってことでおｋ？

**Comment by novagz5** [comment]
バージョンは確認したはず
カレントフォルダにダウンロードする方法がわからない

**Comment by novagz5** [comment]
ダウンロードした後に移動させてるけどできない

**Comment by koki-333** [comment]
C:\Users\userになっているとおもうんだけど、それをcd使ってwhlがあるフォルダを指定する。

**Comment by koki-333** [comment]
あとなんてコマンド入力してる？

**Comment by novagz5** [comment]
![Anaconda Prompt (anaconda3) 2021_09_06 11_55_11](https://user-images.githubusercontent.com/84756510/132155002-35181fa9-8a91-4d84-b4d8-27b2836bb6a6.png)
![Anaconda Prompt (anaconda3) 2021_09_06 11_55_27](https://user-images.githubusercontent.com/84756510/132155003-26ca2764-eb7b-46aa-828b-15062d5e7598.png)
![Anaconda Prompt (anaconda3) 2021_09_06 11_55_36](https://user-images.githubusercontent.com/84756510/132155004-3548bb39-c6ae-4329-b797-3c2e93f5df2f.png)

**Comment by koki-333** [comment]
なるほど、そしたらwhlファイルの名前をコピペして、貼りなおしてみて！
自分も最後のエラー出たけど、これで解決したよ

**Comment by koki-333** [comment]
多分cp38mのmがおかしいんだと思う

**Comment by novagz5** [comment]
できた（笑）そんなくだらないことだったのか...ありがとう＞＜

**Comment by koki-333** [comment]
解決してよかった笑

**Comment by Ishimoto0314** [comment]
それぞれわかったことをなんでもいいので作ったissueに書いておきましょう

**Comment by novagz5** [comment]
僕は書いた通り、ライブラリのインストールに手間がかかってしまいましたが、解決するところまで行けました

**Comment by koki-333** [comment]
振幅スペクトログラムをdBスケールに変換できた。
だが、振幅スペクトログラムとパワースペクトログラムの違いがよくわからない。

**Comment by Ishimoto0314** [comment]
僕は「ゼロから作るDeepLearning」というissueに現状わかったことを書きました

**Comment by novagz5** [comment]
Read me 更新
Tab譜とは？
