### ISSUE TITLE
ロゴを作る

### ISSUE THREAD

**Issue by novagz5** [Ishimoto0314/group4#3]
３人そろったらやりましょう

**Comment by Ishimoto0314** [comment]
了解

**Comment by Ishimoto0314** [comment]
明日か明後日の昼休みと放課後使ってジェネレータで作成しましょう

**Comment by Ishimoto0314** [comment]
ロゴの方は角田君が作ってくれたものがありますがシンプルでいいと思うので、
候補の一つとしていいんではないでしょうか
できれば、音楽要素も入れたいので、よかったら三人で考えてみましょう（ロゴに音符を入れるとか）

**Comment by novagz5** [comment]
了解。多分音楽要素も選択すれば入れられると思う。
チーム名も決まったし作ってみよう

**Comment by Ishimoto0314** [comment]
![logo](https://user-images.githubusercontent.com/84367181/127584680-593d9523-baf5-49dc-bf8c-f256430a166b.png)

**Comment by Ishimoto0314** [comment]
一応作ってみました
真ん中はCDディスクです

**Comment by Ishimoto0314** [comment]
とりあえず決まったのでcloseします
